### ISSUE TITLE
keys.txt

### ISSUE THREAD

**Issue by ray1025** [seiya-dev/NSC_BUILDER#2]
I've already placed keys.txt inside the ztools folder, but it's showing "keys.txt" is not correctly pointed or is missing. What could be the issue?

**Comment by seiya-git** [comment]
@ray1025 put "prod.keys" to "%userprofile%/.switch/"

**Comment by ray1025** [comment]
Okay, it's executable now. However, when I enter the menu, the normal blue screen turns into a black screen. Is there an issue somewhere?

**Comment by ray1025** [comment]
I used the renaming function, and as a result, the file name now includes "(needscheck)."

**Comment by seiya-git** [comment]
Renaming nor fully tested yet

**Comment by ray1025** [comment]
What could be the issue causing the blue background to change into a black background?

https://github.com/seiya-dev/NSC_BUILDER/assets/49980364/1c249af2-ed75-41ee-bae7-827bfae6ba3e

**Comment by seiya-git** [comment]
It's not an issue
